config/routes.php
<?php
/**
 * Routes configuration
 *
 * In this file, you set up routes to your controllers and their actions.
 * Routes are very important mechanism that allows you to freely connect
 * different URLs to chosen controllers and their actions (functions).
 *
 * CakePHP(tm) : Rapid Development Framework (https://cakephp.org)
 * Copyright (c) Cake Software Foundation, Inc. (https://cakefoundation.org)
 *
 * Licensed under The MIT License
 * For full copyright and license information, please see the LICENSE.txt
 * Redistributions of files must retain the above copyright notice.
 *
 * @copyright     Copyright (c) Cake Software Foundation, Inc. (https://cakefoundation.org)
 * @link          https://cakephp.org CakePHP(tm) Project
 * @license       https://opensource.org/licenses/mit-license.php MIT License
 */
use Cake\Http\Middleware\CsrfProtectionMiddleware;
use Cake\Routing\RouteBuilder;
use Cake\Routing\Router;
use Cake\Routing\Route\DashedRoute;

/**
 * The default class to use for all routes
 *
 * The following route classes are supplied with CakePHP and are appropriate
 * to set as the default:
 *
 * - Route
 * - InflectedRoute
 * - DashedRoute
 *
 * If no call is made to `Router::defaultRouteClass()`, the class used is
 * `Route` (`Cake\Routing\Route\Route`)
 *
 * Note that `Route` does not do any inflections on URLs which will result in
 * inconsistently cased URLs when used with `:plugin`, `:controller` and
 * `:action` markers.
 *
 * Cache: Routes are cached to improve performance, check the RoutingMiddleware
 * constructor in your `src/Application.php` file to change this behavior.
 *
 */
Router::defaultRouteClass(DashedRoute::class);

Router::scope('/', function (RouteBuilder $routes) {
    // Register scoped middleware for in scopes.
    $routes->registerMiddleware('csrf', new CsrfProtectionMiddleware([
        'httpOnly' => true
    ]));

    /**
     * Apply a middleware to the current route scope.
     * Requires middleware to be registered via `Application::routes()` with `registerMiddleware()`
     */
    $routes->applyMiddleware('csrf');

    /**
     * Here, we are connecting '/' (base path) to a controller called 'Pages',
     * its action called 'display', and we pass a param to select the view file
     * to use (in this case, src/Template/Pages/home.ctp)...
     */
    $routes->connect('/', ['controller' => 'EmployeeInformation', 'action' => 'home', 'home']);

    /**
     * EmployeeInformation controller
     */
    $routes->connect('/login', ['controller' => 'EmployeeInformation', 'action' => 'login']);    
    $routes->connect('/employees', ['controller' => 'EmployeeInformation', 'action' => 'index']);
    $routes->connect('/employees/add', [
            'controller' => 'EmployeeInformation',
            'action' => 'add'
        ]
    );
    $routes->connect('/employees/edit/:id', [
            'controller' => 'EmployeeInformation',
            'action' => 'edit'
        ], 
        [
            'pass' => ['id'], 
            'id' => '[0-9]+'
        ]
    );

    /**
     * LeaveApplications controller
     */
    $routes->connect('/leaves', [
            'controller' => 'LeaveApplications',
            'action' => 'index'
        ]
    );
    $routes->connect('/leaves/apply', [
            'controller' => 'LeaveApplications',
            'action' => 'add'
        ]
    );
    $routes->connect('/leaves/edit/:id', [
            'controller' => 'LeaveApplications',
            'action' => 'edit'
        ], 
        [
            'pass' => ['id'], 
            'id' => '[0-9]+'
        ]
    );
    $routes->connect('/leaves/view/:id', [
            'controller' => 'LeaveApplications',
            'action' => 'view'
        ], 
        [
            'pass' => ['id'], 
            'id' => '[0-9]+'
        ]
    );
    $routes->connect('/leaves/generateReport', [
            'controller' => 'LeaveApplications',
            'action' => 'generateReport'
        ]
    );
    $routes->connect('/leaves/cancel/:id', [
            'controller' => 'LeaveApplications',
            'action' => 'cancel'
        ], 
        [
            'pass' => ['id'], 
            'id' => '[0-9]+'
        ]
    );
    /**
     * LeaveApplicationResponses controller
     */
    $routes->connect('/leave_response/add', [
            'controller' => 'LeaveApplicationResponses',
            'action' => 'add'
        ]
    );

    /**
     * Terms controller
     */
    $routes->connect('/terms/add', [
            'controller' => 'Terms',
            'action' => 'add'
        ]
    );

    /**
     * ...and connect the rest of 'Pages' controller's URLs.
     */
    $routes->connect('/pages/*', ['controller' => 'Pages', 'action' => 'display']);

    /**
     * Connect catchall routes for all controllers.
     *
     * Using the argument `DashedRoute`, the `fallbacks` method is a shortcut for
     *
     * ```
     * $routes->connect('/:controller', ['action' => 'index'], ['routeClass' => 'DashedRoute']);
     * $routes->connect('/:controller/:action/*', [], ['routeClass' => 'DashedRoute']);
     * ```
     *
     * Any route class can be used with this method, such as:
     * - DashedRoute
     * - InflectedRoute
     * - Route
     * - Or your own route class
     *
     * You can remove these routes once you've connected the
     * routes you want in your application.
     */
    $routes->fallbacks(DashedRoute::class);
});

/**
 * If you need a different set of middleware or none at all,
 * open new scope and define routes there.
 *
 * ```
 * Router::scope('/api', function (RouteBuilder $routes) {
 *     // No $routes->applyMiddleware() here.
 *     // Connect API actions here.
 * });
 * ```
 */

src/Model/Entity/LeaveApplication.php
<?php
namespace App\Model\Entity;

use Cake\ORM\Entity;

/**
 * LeaveApplication Entity
 *
 * @property int $id
 * @property int $employee_id
 * @property int $leave_type_id
 * @property int|null $leave_category_id
 * @property string|null $leave_description
 * @property int|null $applied_for
 * @property string $leave_from
 * @property string $leave_to
 * @property int|null $commutation
 * @property int|null $is_success
 * @property \Cake\I18n\FrozenTime $created
 * @property \Cake\I18n\FrozenTime $modified
 * @property \Cake\I18n\FrozenTime|null $deleted_date
 * @property int|null $deleted
 *
 * @property \App\Model\Entity\Employee $employee
 * @property \App\Model\Entity\LeaveType $leave_type
 * @property \App\Model\Entity\LeaveCategory $leave_category
 */
class LeaveApplication extends Entity
{
    /**
     * Fields that can be mass assigned using newEntity() or patchEntity().
     *
     * Note that when '*' is set to true, this allows all unspecified fields to
     * be mass assigned. For security purposes, it is advised to set '*' to false
     * (or remove it), and explicitly make individual fields accessible as needed.
     *
     * @var array
     */
    protected $_accessible = [
        'employee_id' => true,
        'leave_type_id' => true,
        'leave_category_id' => true,
        'leave_description' => true,
        'applied_for' => true,
        'leave_from' => true,
        'leave_to' => true,
        'commutation' => true,
        'is_success' => true,
        'leave_status' => true,
        'created' => true,
        'modified' => true,
        'deleted_date' => true,
        'deleted' => true,
        'employee' => true,
        'leave_type' => true,
        'leave_category' => true
    ];
}

src/Model/Table/LeaveApplicationsTable.php
<?php
namespace App\Model\Table;

use Cake\ORM\Query;
use Cake\ORM\RulesChecker;
use Cake\ORM\Table;
use Cake\Validation\Validator;

/**
 * LeaveApplications Model
 *
 * @property \App\Model\Table\EmployeeInformationTable|\Cake\ORM\Association\BelongsTo $EmployeeInformation
 * @property \App\Model\Table\LeaveTypesTable|\Cake\ORM\Association\BelongsTo $LeaveTypes
 * @property \App\Model\Table\LeaveCategoriesTable|\Cake\ORM\Association\BelongsTo $LeaveCategories
 *
 * @method \App\Model\Entity\LeaveApplication get($primaryKey, $options = [])
 * @method \App\Model\Entity\LeaveApplication newEntity($data = null, array $options = [])
 * @method \App\Model\Entity\LeaveApplication[] newEntities(array $data, array $options = [])
 * @method \App\Model\Entity\LeaveApplication|bool save(\Cake\Datasource\EntityInterface $entity, $options = [])
 * @method \App\Model\Entity\LeaveApplication saveOrFail(\Cake\Datasource\EntityInterface $entity, $options = [])
 * @method \App\Model\Entity\LeaveApplication patchEntity(\Cake\Datasource\EntityInterface $entity, array $data, array $options = [])
 * @method \App\Model\Entity\LeaveApplication[] patchEntities($entities, array $data, array $options = [])
 * @method \App\Model\Entity\LeaveApplication findOrCreate($search, callable $callback = null, $options = [])
 *
 * @mixin \Cake\ORM\Behavior\TimestampBehavior
 */
class LeaveApplicationsTable extends Table
{
    /**
     * Initialize method
     *
     * @param array $config The configuration for the Table.
     * @return void
     */
    public function initialize(array $config)
    {
        parent::initialize($config);

        $this->setTable('leave_applications');
        $this->setDisplayField('id');
        $this->setPrimaryKey('id');

        $this->addBehavior('Timestamp');

        $this->belongsTo('EmployeeInformation', [
            'foreignKey' => 'employee_id',
            'joinType' => 'INNER'
        ]);
        $this->belongsTo('LeaveTypes', [
            'foreignKey' => 'leave_type_id',
            'joinType' => 'INNER'
        ]);
        $this->belongsTo('LeaveCategories', [
            'foreignKey' => 'leave_category_id'
        ]);
        $this->hasOne('LeaveApplicationResponses', [
            'foreignKey' => 'application_id'
        ]);
    }

    /**
     * Default validation rules.
     *
     * @param \Cake\Validation\Validator $validator Validator instance.
     * @return \Cake\Validation\Validator
     */
    public function validationDefault(Validator $validator)
    {
        $validator
            ->integer('id')
            ->allowEmptyString('id', 'create');

        $validator
            ->scalar('leave_description')
            ->maxLength('leave_description', 255)
            ->allowEmptyString('leave_description');

        $validator
            ->integer('applied_for')
            ->allowEmptyString('applied_for');
        
        $validator
            ->integer('leave_type_id')    
            ->requirePresence('leave_type_id', 'create')
            ->notEmptyString('leave_type_id', 'Leave type must not be empty');

        $validator
            ->scalar('leave_from', 'mdy')
            ->maxLength('leave_from', 255)
            ->requirePresence('leave_from', 'create')
            ->notEmptyString('leave_from', 'Leave from must not be empty');

        $validator
            ->scalar('leave_to', 'mdy')
            ->maxLength('leave_to', 255)
            ->requirePresence('leave_to', 'create')
            ->notEmptyString('leave_to', 'Leave to must not be empty');

        $validator
            ->integer('commutation')
            ->notEmptyString('commutation', 'Commutation must not be empty');

        $validator
            ->integer('is_success')
            ->allowEmptyString('is_success');

        $validator
            ->dateTime('deleted_date')
            ->allowEmptyDateTime('deleted_date');

        $validator
            ->integer('deleted')
            ->allowEmptyString('deleted');

        return $validator;
    }

    /**
     * Returns a rules checker object that will be used for validating
     * application integrity.
     *
     * @param \Cake\ORM\RulesChecker $rules The rules object to be modified.
     * @return \Cake\ORM\RulesChecker
     */
    public function buildRules(RulesChecker $rules)
    {
        $rules->add($rules->existsIn(['employee_id'], 'EmployeeInformation'));
        $rules->add($rules->existsIn(['leave_type_id'], 'LeaveTypes'));
        $rules->add($rules->existsIn(['leave_category_id'], 'LeaveCategories'));

        return $rules;
    }
}

src/Template/LeaveApplications/generate_report.ctp
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
<?php foreach($leaveApplications as $leave) : ?>
<div class="container" style="page-break-after: always;">
  <div class="row">
    <div class="col-sm">CS Form No. 6</div>
  </div>
  <div class="row">
    <div class="col-sm">Revised 1984</div>
  </div>
  <div class="row">
    <div class="col-sm-12 text-center">APPLICATION FOR LEAVE</div>
  </div>
  </br>
  <div class="row border-top border-left border-right">
    <div class="col-sm">1. OFFICE/ AGENCY</div>
    <div class="col-sm">2. NAME(LAST)</div>
    <div class="col-sm">(FIRST)</div>
    <div class="col-sm">(MIDDLE)</div>
  </div>
  <div class="row border-bottom border-left border-right">
    <div class="col-sm">BULIHAN N.H.S.</div>
    <div class="col-sm"><?= $leave->employee_information->last_name ?></div>
    <div class="col-sm"><?= $leave->employee_information->first_name ?></div>
    <div class="col-sm"><?= $leave->employee_information->middle_name ?></div>
  </div>
  <div class="row">
    <div class="col-sm-3">3. DATE OF FILING </div>
    <div class="col-sm-3">4. POSITION </div>
    <div class="col-sm-6">5. SALARY (MONTHLY)</div>
  </div>
  <div class="row">
    <div class="col-sm-3"><?= $leave->created->i18nFormat('YYYY-MM-dd') ?></div>
    <div class="col-sm-3"><?= $leave->employee_information->job_position->title ?></div>
    <div class="col-sm-6"><?= $leave->employee_information->salary ?></div>
  </div>
  <div class="row border border-dark">
    <div class="col-sm-4">6.</div>
    <div class="col-sm-8">DETAILS OF APPLICATION</div>
  </div>
  </br>
  <div class="row">
    <div class="col-sm">6. a) TYPE OF LEAVE</div>
    <div class="col-sm">6. b) WHERE LEAVE WILL BE SPENT</div>
  </div>
  <div class="row">
    <div class="col-sm"></div>
    <div class="col-sm border box"><?= $leave->leave_type_id == 1 ? '/' : '' ?></div>
    <div class="col-sm-4">VACATION</div>
    <div class="col-sm-6">(1) IN CASE OF VACATION LEAVE</div>
  </div>
  <div class="row">
    <div class="col-sm"></div>
    <div class="col-sm border box"><?= $leave->leave_type_id == 3 ? '/' : '' ?></div>
    <div class="col-sm-4">TO SEEK EMPLOYMENT</div>
    <div class="col-sm border box"><?= $leave->leave_category_id == 1 ? '/' : '' ?></div>
    <div class="col-sm-5">WITH IN THE PHILIPPINES</div>
  </div>
  <div class="row">
    <div class="col-sm-2"></div>
    <div class="col-sm-2">OTHERS(specify)</div>
    <div class="col-sm-2 border-bottom"><?= $leave->leave_description ?></div>
    <div class="col-sm border box"><?= $leave->leave_category_id == 2 ? '/' : '' ?></div>
    <div class="col-sm-2">ABROAD (SPECIFY)</div>
    <div class="col-sm-3 border-bottom"><?= $leave->leave_description ?></div>
  </div>
  <div class="row">
    <div class="col-sm-2"></div>
    <div class="col-sm-4 border-bottom">.</div>
    <div class="col-sm-2"></div>
    <div class="col-sm-4 border-bottom">.</div>
  </div>
  <div class="row">
    <div class="col-sm"><?= $leave->leave_type_id == 2 ? '/' : '' ?></div>
    <div class="col-sm border box"></div>
    <div class="col-sm-10">SICK</div>
  </div>
  <div class="row">
    <div class="col-sm"></div>
    <div class="col-sm border box"><?= $leave->leave_type_id == 4 ? '/' : '' ?></div>
    <div class="col-sm-4">MATERNITY</div>
    <div class="col-sm-6">(2) IN CASE OF SICK LEAVE</div>
  </div>
  <div class="row">
    <div class="col-sm"></div>
    <div class="col-sm border box"><?= $leave->leave_type_id == 5 ? '/' : '' ?></div>
    <div class="col-sm-4">OTHERS(specify)</div>
    <div class="col-sm border box"><?= $leave->leave_category_id == 3 ? '/' : '' ?></div>
    <div class="col-sm-5">IN HOSPITAL(specify)</div>
  </div>
  </br>
  <div class="row">
    <div class="col-sm-6"></div>
    <div class="col-sm border box"><?= $leave->leave_category_id == 4 ? '/' : '' ?></div>
    <div class="col-sm-3">OUTPATIENT (Specify)</div>
    <div class="col-sm-2 border-bottom"><?= $leave->leave_description ?></div>
  </div>
  <div class="row">
    <div class="col-sm-7"></div>
    <div class="col-sm-5 border-bottom">.</div>
  </div>
  </br>
  <div class="row">
    <div class="col-sm">6. c) NUMBER OF WORKING DAYS</div>
    <div class="col-sm">6. d) COMMUTATION</div>
  </div>
  <div class="row">
    <div class="col-sm"></div>
    <div class="col-sm-2">APPLIED FOR</div>
    <div class="col-sm-3 border-bottom"><?= $leave->applied_for ?></div>
    <div class="col-sm-6"></div>
  </div>
  <div class="row">
    <div class="col-sm"></div>
    <div class="col-sm-2">INCLUSIVE DATES</div>
    <div class="col-sm-3 border-bottom"><?= $leave->applied_from . '-' . $leave->applied_to ?></div>
    <div class="col-sm border box"><?= $leave->commutation == 1 ? '/' : '' ?></div>
    <div class="col-sm-2">requested</div>
    <div class="col-sm border box"><?= $leave->commutation == 2 ? '/' : '' ?></div>
    <div class="col-sm-2">not requested</div>
  </div>
  </br>
  </br>
  </br>
  <div class="row">
    <div class="col-sm-7"></div>
    <div class="col-sm">(Signature of Applicant)</div>
  </div>
  </br>
  <div class="row border border-dark">
    <div class="col-sm-4">7.</div>
    <div class="col-sm-8">DETAILS ON ACTION OF APPLICATION</div>
  </div>
  </br>
  <div class="row">
    <div class="col-sm">7. a) CERTIFICATION OF LEAVE CREDITS</div>
    <div class="col-sm">7. b) RECOMMENDATION</div>
  </div>
  <div class="row">
    <div class="col-sm"></div>
    <div class="col-sm">AS OF</div>
    <div class="col-sm-4 border-bottom">.</div>
    <div class="col-sm border box"><?= $leave->leave_status == 2 ? '/' : '' ?></div>
    <div class="col-sm-2">APPROVAL</div>
    <div class="col-sm-3"></div>
  </div>
  <div class="row">
    <div class="col-sm-6"></div>
    <div class="col-sm border box"><?= $leave->leave_status == 4 ? '/' : '' ?></div>
    <div class="col-sm-2">DISAPPROVAL DUE TO</div>
    <div class="col-sm-3"></div>
  </div>
  <div class="row">
    <div class="col-sm"></div>
    <div class="col-sm border-top border-left border-right border-thick text-center">VACATION</div>
    <div class="col-sm border-top border-left border-right border-thick text-center">SICK</div>
    <div class="col-sm border-top border-left border-right border-thick text-center">TOTAL</div>
    <div class="col-sm"></div>
    <div class="col-sm-5 border-bottom"><?= $leave->leave_application_response->recommendation_description ?></div>
  </div>
  <div class="row">
    <div class="col-sm">.</div>
    <div class="col-sm border-left border-right border-thick"></div>
    <div class="col-sm border-left border-right border-thick"></div>
    <div class="col-sm border-left border-right border-thick"></div>
    <div class="col-sm"></div>
    <div class="col-sm-5 border-bottom"></div>
  </div>
  <div class="row">
    <div class="col-sm"></div>
    <div class="col-sm border-bottom border-left border-right border-thick text-center">DAYS</div>
    <div class="col-sm border-bottom border-left border-right border-thick text-center">DAYS</div>
    <div class="col-sm border-bottom border-left border-right border-thick text-center">DAYS</div>
    <div class="col-sm"></div>
    <div class="col-sm-5"></div>
  </div>
  </br>
  </br>
  </br>
  </br>
  <div class="row">
    <div class="col-sm text-center">VERNA C. CABAYA</div>
    <div class="col-sm text-center">CRISTINA M. AUSTRIA</div>
  </div>
  <div class="row">
    <div class="col-sm text-center">ADMINISTRATIVE OFFICER V</div>
    <div class="col-sm text-center">PRINCIPAL IV</div>
  </div>
  </br>
  </br>
  </br>
  <div class="row">
    <div class="col-sm">7. c) APPROVED FOR:</div>
    <div class="col-sm">7. d) DISAPPROVED DUE TO:</div>
  </div>
  <div class="row">
    <div class="col-sm border-bottom"></div>
    <div class="col-sm-5">DAYS WITH PAY</div>
    <div class="col-sm-6 border-bottom"></div>
  </div>
  <div class="row">
    <div class="col-sm border-bottom"></div>
    <div class="col-sm-5">DAYS WITHOUT PAY</div>
    <div class="col-sm-6 border-bottom"></div>
  </div>
  <div class="row">
    <div class="col-sm border-bottom"></div>
    <div class="col-sm-5">OTHER (Specify)</div>
    <div class="col-sm-6 border-bottom"></div>
  </div>
  </br>
  </br>
  <div class="row">
    <div class="col-sm-12 text-center">ELIAS A. ALICAYA JR, Ed.D.</div>
  </div>
  <div class="row">
    <div class="col-sm-4"></div>
    <div class="col-sm-4 border-bottom text-center">Assistant Schools Division Superintendent</div>
    <div class="col-sm-4"></div>
  </div>
  <div class="row">
    <div class="col-sm-12 text-center">(Signature)</div>
  </div>
  </br>
  <div class="row">
    <div class="col-sm-4"></div>
    <div class="col-sm-4 border-bottom text-center">.</div>
    <div class="col-sm-4"></div>
  </div>
  </br>
  <div class="row">
    <div class="col-sm">DATE: <?= date('Y-m-d') ?></div>
  </div>
</div>
<?php endforeach; ?>
<style type="text/css">
  .box {
    border: 2px solid black !important;
    text-align: center !important;
  }

  .border-left {
    border-left: solid 1px black !important;
  }

  .border-right {
    border-right: solid 1px black !important;
  }

  .border-top {
    border-top: solid 1px black !important;
  }

  .border-bottom {
    border-bottom: solid 1px black !important;
  }

  .border-thick {
    border-width: 2px !important;
  }
</style>

src/Template/LeaveApplications/index.ctp
<?php $this->assign('title', 'Home'); ?> 
<div class="content-wrapper">
  <section class="content-header">
    <h1>
      Leaves List
    </h1>
    <ol class="breadcrumb">
      <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
      <li><a href="#">Leaves List</a></li>
    </ol>
  </section>

  <section class="content">
    <div class="row">
      <div class="col-md-12">
        <?= $this->Flash->render(); ?>
        <button type="button" class="btn btn-primary btn-md" id="btn-generate-report">
          Generate Report
        </button><br><br>
        <div class="box">
          <div class="box-header">
            <h3 class="box-title">Recent Applications</h3>
          </div>
          <div class="box-body">
            <table id="employee_list" class="table table-bordered table-striped">
              <thead>
                <tr>
                  <th>Application ID</th>
                  <th>Employee Name</th>
                  <th>Application Type</th>
                  <th>Overview Date</th>
                  <th>Status</th>
                  <th class="actions"><?= __('Actions') ?></th>
                </tr>
              </thead>
              <tbody>
                <?php foreach ($leaveApplications as $leaveApplication) : ?>
                  <tr>
                    <td><?= $leaveApplication->id ?></td>
                    <td><?= h($leaveApplication->employee_information->last_name . ', ' .
                            $leaveApplication->employee_information->first_name . ' ' . 
                            $leaveApplication->employee_information->middle_name) ?></td>
                    <td><?= $leaveTypes[$leaveApplication->leave_type_id] ?></td>
                    <td><?= $leaveApplication->leave_from . ' - ' . $leaveApplication->leave_to ?></td>
                    <td>
                      <?php if ($leaveApplication->leave_status == $this->Configure->read('LEAVES.STATUS.ForApproval')) : ?>
                        <span class="badge bg-white">For Approval</span>
                      <?php elseif ($leaveApplication->leave_status == $this->Configure->read('LEAVES.STATUS.Approved')) :?>
                        <span class="badge bg-green">Approved</span>
                      <?php elseif ($leaveApplication->leave_status == $this->Configure->read('LEAVES.STATUS.Cancelled')) :?>
                        <span class="badge bg-yellow">Cancelled</span>
                      <?php elseif ($leaveApplication->leave_status == $this->Configure->read('LEAVES.STATUS.Disapproved')) :?>
                        <span class="badge bg-red">Disapproved</span>
                      <?php endif; ?>
                    </td>
                    <td class="actions">
                      <a href="/leaves/view/<?= $leaveApplication->id?>" class="btn btn-default"><i class="fa fa-eye"></i></a>
                    </td>
                  </tr>
                <?php endforeach ?>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </section>
</div>

<script type="text/javascript">
  $('#btn-generate-report').on('click', function() {
    window.open('/leaves/generateReport','_blank');
  });
</script>